---
- name: touch files
  hosts: localhost
  gather_facts: false

  tasks: 
    - include: files.yaml
      path: /tmp/foo
      file: herp

    - include: files.yaml
      path: /tmp/foo
      file: derp
