---
- name: error handling
  hosts: localhost
  gather_facts: false

  tasks:
    - name: check if branch badfeature exists
      command: git branch
      args:
        chdir: /srv/app
      register: branches

    - name: delete branch bad
      command: git branch -D badfeature
      args:
        chdir: /srv/app
      when: branches.stdout | search('badfeature')
