---
- name: demo the template
  hosts: localhost
  gather_facts: false

  vars:
    data_dirs: []

  tasks:
    - name: pause with render
      pause:
        prompt: "{{ lookup('template', 'demo.j2') }}"
