---
- name: test remote_copy module
  hosts: localhost
  gather_facts: false

  tasks:
    - name: ensure foo
      file:
        path: /tmp/foo
        state: touch

    - name: do a remote copy
      remote_copy:
        source: /tmp/foo
        dest: /tmp/bar
