---
- name: error handling
  hosts: localhost
  gather_facts: false

  tasks:
    - name: discover tango directory
      stat: path=/srv/whiskey/tango
      register: tango

    - name: run frobitz
      script: files/frobitz --initialize /srv/whiskey/tango
      when: not tango.stat.exists
