---
- name: demo the filters
  hosts: localhost
  gather_facts: false

  tasks:
    - name: fail a task
      debug:
        msg: "I am not a change"
      register: derp

    - name: only do this on change
      debug:
        msg: "You had a change"
      when: derp | changed

    - name: only do this on success
      debug:
        msg: "You had a success"
      when: derp | success
