---
- name: task inclusion
  hosts: localhost
  gather_facts: false

  tasks:
    - include: more-tasks.yaml
        data: first
      tags: first

    - include: more-tasks.yaml
        data: second
      tags: second
